In [2]:
import networkx as nx
import numpy as np
from scipy.linalg import expm
import pickle
import pandas as pd

## check saved kernels

In [4]:
kernel_dict_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/path_save.pkl'
with open(kernel_dict_path, 'rb') as f:
    kernels_all_dict = pickle.load(f)
kernels_all_dict

{'ppi_2019_dw_40': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/ppi_2019_dw_40_K_2_0.10641570688646294.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/ppi_2019_dw_40_logK_2_0.10641570688646294.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/ppi_2019_dw_40_K_4_0.05320785344323147.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/ppi_2019_dw_40_logK_4_0.05320785344323147.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/ppi_2019_dw_40_K_8_0.026603926721615736.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/ppi_2019_dw_40_logK_8_0.026603926721615736.pkl']},
 'uniport_ppi_2019': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_ppi_2019_K_2_0.11730356420617227.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_ppi_2019_logK_2_0.11730356420617227.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_ppi_2019_K_4_0.058651782103086136.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_ppi_2019_logK_4_0.058651782103086136.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_ppi_2019_K_8_0.029325891051543068.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_ppi_2019_logK_8_0.029325891051543068.pkl']},
 'uniport_bio': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_bio_K_2_0.05853505840227169.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_bio_logK_2_0.05853505840227169.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_bio_K_4_0.029267529201135845.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_bio_logK_4_0.029267529201135845.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_bio_K_8_0.014633764600567922.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_bio_logK_8_0.014633764600567922.pkl']},
 'uniport_esm': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_esm_K_2_0.33953686194404037.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_esm_logK_2_0.33953686194404037.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_esm_K_4_0.16976843097202018.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_esm_logK_4_0.16976843097202018.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_esm_K_8_0.08488421548601009.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_esm_logK_8_0.08488421548601009.pkl']},
 'uniport_seq': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_seq_K_2_1.7324380888454085.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_seq_logK_2_1.7324380888454085.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_seq_K_4_0.8662190444227043.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_seq_logK_4_0.8662190444227043.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_seq_K_8_0.4331095222113521.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_seq_logK_8_0.4331095222113521.pkl']}}

In [5]:
kernel_dict_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/path_save.pkl'
with open(kernel_dict_path, 'rb') as f:
    kernels_all_dict = pickle.load(f)
kernels_all_dict

{'uniport_esm': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_2_0.11355235622105712.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_2_0.11355235622105712.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_4_0.05677617811052856.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_4_0.05677617811052856.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_8_0.02838808905526428.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_8_0.02838808905526428.pkl']},
 'uniport_bio': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_2_0.5427586367192363.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_2_0.5427586367192363.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_4_0.27137931835961815.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_4_0.27137931835961815.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_8_0.13568965917980907.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_8_0.13568965917980907.pkl']},
 'uniport_seq': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_2_0.22444018226022353.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_2_0.22444018226022353.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_4_0.11222009113011176.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_4_0.11222009113011176.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_8_0.05611004556505588.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_8_0.05611004556505588.pkl']},
 'ppi_2019_dw_40': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_2_0.48138034733416246.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_2_0.48138034733416246.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_4_0.24069017366708123.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_4_0.24069017366708123.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_8_0.12034508683354062.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_8_0.12034508683354062.pkl']},
 'diffusion_2019': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/diffusion_2019_K_2_0.5.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/diffusion_2019_logK_2_0.5.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/diffusion_2019_K_4_0.25.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/diffusion_2019_logK_4_0.25.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/diffusion_2019_K_8_0.125.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/diffusion_2019_logK_8_0.125.pkl']},
 'uniport_ppi_2019': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_2_0.5052695526173884.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_2_0.5052695526173884.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_4_0.2526347763086942.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_4_0.2526347763086942.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_8_0.1263173881543471.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_8_0.1263173881543471.pkl']}}

In [3]:
for key in kernels_all_dict.keys():
    for g in kernels_all_dict[key].keys():
        k_path = kernels_all_dict[key][g][0]
        with open(k_path, 'rb') as f:
            matrix = pickle.load(f)
        print(k_path.split('/')[-1],np.min(matrix),np.max(matrix))

uniport_esm_K_2_0.11355235622105712.pkl 5.074694312794253e-10 1.0
uniport_esm_K_4_0.05677617811052856.pkl 2.2527082174117123e-05 1.0
uniport_esm_K_8_0.02838808905526428.pkl 0.004746270343555782 1.0
uniport_bio_K_2_0.5427586367192363.pkl 0.010129128494567152 1.0
uniport_bio_K_4_0.27137931835961815.pkl 0.10064357155112864 1.0
uniport_bio_K_8_0.13568965917980907.pkl 0.31724371002610696 1.0
uniport_seq_K_2_0.22444018226022353.pkl 5.112442244191493e-20 1.0
uniport_seq_K_4_0.11222009113011176.pkl 2.2610710391740223e-10 1.0
uniport_seq_K_8_0.05611004556505588.pkl 1.5036858179732968e-05 1.0
ppi_2019_dw_40_K_2_0.48138034733416246.pkl 0.02026948259827836 1.0
ppi_2019_dw_40_K_4_0.24069017366708123.pkl 0.14237093312287574 1.0
ppi_2019_dw_40_K_8_0.12034508683354062.pkl 0.37732072978154246 1.0
diffusion_2019_K_2_0.5.pkl 0.0 1.0
diffusion_2019_K_4_0.25.pkl 0.0 1.0
diffusion_2019_K_8_0.125.pkl 0.0 1.0
uniport_ppi_2019_K_2_0.5052695526173884.pkl 0.015619794758873148 1.0
uniport_ppi_2019_K_4_0.2526347763086942.pkl 0.12497917730115345 1.0
uniport_ppi_2019_K_8_0.1263173881543471.pkl 0.3535239416236946 1.0

## clearly something wrong with diffusion kernel

that's because calculating kernel along with other features

but actially diffusion kernels need another way to calcualte. 

and we already calculated in /itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019 using diffusion.py file

In [6]:
import os

df_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019'
df_dict = dict()
for file in os.listdir(df_path):
    if 'uniport_diffusion_K' in file:
        temp_list = []
        key = file.split('_')[-1][:-4]
        temp_list.append(os.path.join(df_path,file))
        temp_list.append(os.path.join(df_path,'uniport_diffusion_logK_'+file.split('_')[-1]))
        df_dict[key] = temp_list

In [8]:
kernels_all_dict.keys()

dict_keys(['uniport_esm', 'uniport_bio', 'uniport_seq', 'ppi_2019_dw_40', 'diffusion_2019', 'uniport_ppi_2019'])

In [10]:
df_dict.keys()

dict_keys(['0.2', '1', '0.5', '2', '0.1', '0.8'])

In [12]:
df_dict['1']

['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_1.pkl',
 '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_1.pkl']

In [13]:
del kernels_all_dict['diffusion_2019']
kernels_all_dict.keys()

dict_keys(['uniport_esm', 'uniport_bio', 'uniport_seq', 'ppi_2019_dw_40', 'uniport_ppi_2019'])

In [14]:
kernels_all_dict['diffusion_kernel'] = df_dict
kernels_all_dict.keys()

dict_keys(['uniport_esm', 'uniport_bio', 'uniport_seq', 'ppi_2019_dw_40', 'uniport_ppi_2019', 'diffusion_kernel'])

In [15]:
kernel_dict_path

'/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/path_save.pkl'

In [16]:
kernels_all_dict

{'uniport_esm': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_2_0.11355235622105712.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_2_0.11355235622105712.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_4_0.05677617811052856.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_4_0.05677617811052856.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_8_0.02838808905526428.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_8_0.02838808905526428.pkl']},
 'uniport_bio': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_2_0.5427586367192363.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_2_0.5427586367192363.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_4_0.27137931835961815.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_4_0.27137931835961815.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_8_0.13568965917980907.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_8_0.13568965917980907.pkl']},
 'uniport_seq': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_2_0.22444018226022353.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_2_0.22444018226022353.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_4_0.11222009113011176.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_4_0.11222009113011176.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_8_0.05611004556505588.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_8_0.05611004556505588.pkl']},
 'ppi_2019_dw_40': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_2_0.48138034733416246.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_2_0.48138034733416246.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_4_0.24069017366708123.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_4_0.24069017366708123.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_8_0.12034508683354062.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_8_0.12034508683354062.pkl']},
 'uniport_ppi_2019': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_2_0.5052695526173884.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_2_0.5052695526173884.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_4_0.2526347763086942.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_4_0.2526347763086942.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_8_0.1263173881543471.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_8_0.1263173881543471.pkl']},
 'diffusion_kernel': {'0.2': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.2.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.2.pkl'],
  '1': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_1.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_1.pkl'],
  '0.5': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.5.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.5.pkl'],
  '2': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_2.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_2.pkl'],
  '0.1': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.1.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.1.pkl'],
  '0.8': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.8.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.8.pkl']}}

In [17]:
with open(kernel_dict_path, 'wb') as f:
    pickle.dump(kernels_all_dict, f)

In [19]:
kernel_dict_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/path_save.pkl'
with open(kernel_dict_path, 'rb') as f:
    kernels_all_dict = pickle.load(f)
kernels_all_dict.keys()

dict_keys(['uniport_esm', 'uniport_bio', 'uniport_seq', 'ppi_2019_dw_40', 'uniport_ppi_2019', 'diffusion_kernel'])

In [ ]:

kernels_all_dict['diffusion_2019'] = kernels_all_dict['diffusion_kernel']
del kernels_all_dict['diffusion_kernel']
kernels_all_dict.keys()

dict_keys(['uniport_esm', 'uniport_bio', 'uniport_seq', 'ppi_2019_dw_40', 'uniport_ppi_2019', 'diffusion_2019'])

In [22]:
with open(kernel_dict_path, 'wb') as f:
    pickle.dump(kernels_all_dict, f)

## over, below was old code

In [ ]:
def diffusion_kernel(G, beta=0.1, normalized=True):

    if normalized:
        L = nx.normalized_laplacian_matrix(G).todense()
    else:
        L = nx.laplacian_matrix(G).todense()
    
    K = expm(-beta * L)

    return np.array(K)

In [4]:
file_path = '/itf-fi-ml/shared/users/ziyuzh/svm/data/ppi_full_2019.txt'
G = nx.read_edgelist(file_path, nodetype=str, create_using=nx.Graph())

In [5]:
K = diffusion_kernel(G, beta=0.5)

In [6]:
K.shape

(19576, 19576)

In [10]:
nodes = list(G.nodes())
nodes[:2]

['9606.ENSP00000000233', '9606.ENSP00000263431']

In [11]:


i = nodes.index('9606.ENSP00000000233')
j = nodes.index('9606.ENSP00000263431')
print("Similarity:", K[i, j])

Similarity: 0.00016534348491191748

In [29]:
sim_matrix = np.array([
    [1.0, 0.8, 0.75, 0.3, 0.6],
    [0.8, 1.0, 0.9, 0.4, 0.7],
    [0.75, 0.9, 1.0, 0.5, 0.65],
    [0.3, 0.4, 0.5, 1.0, 0.2],
    [0.6, 0.7, 0.65, 0.2, 1.0]
])

In [32]:
import pandas as pd
import numpy as np

# Sample inputs
sim_matrix = np.array([
    [1.0, 0.8, 0.75, 0.3, 0.6],
    [0.8, 1.0, 0.9, 0.4, 0.7],
    [0.75, 0.9, 1.0, 0.5, 0.65],
    [0.3, 0.4, 0.5, 1.0, 0.2],
    [0.6, 0.7, 0.65, 0.2, 1.0]
])
sample_names = ['S0', 'S1', 'S2', 'S3', 'S4']

# Inputs for merging and deletion
merge_groups = [['S1', 'S2']]
delete_list = ['S3']

# Step 1: Convert to tidy format
df = pd.DataFrame(sim_matrix, index=sample_names, columns=sample_names)
tidy = df.stack().reset_index()
tidy.columns = ['Sample_i', 'Sample_j', 'Similarity']
tidy = tidy[tidy['Sample_i'] < tidy['Sample_j']]  # remove duplicates

# Step 2: Precompute all pair similarities
# For quick lookup, use frozen set of pair as key
pair_sim = {
    frozenset([i, j]): s for i, j, s in tidy.itertuples(index=False)
}

# Step 3: Build new groups
sample_to_group = {}
new_names = []
for idx, group in enumerate(merge_groups):
    new_name = '_'.join(sorted(group))
    new_names.append(new_name)
    for s in group:
        sample_to_group[s] = new_name

# Samples not in any merge group or deletion
all_samples = set(sample_names)
merged_samples = set(sample_to_group.keys())
kept_samples = sorted(all_samples - merged_samples - set(delete_list))

# Step 4: Build final sample list and group mapping
final_samples = new_names + kept_samples
group_map = {name: [name] for name in kept_samples}
for group in merge_groups:
    group_name = '_'.join(sorted(group))
    group_map[group_name] = group

# Step 5: Compute average similarity between groups
records = []
for i, group_i in enumerate(final_samples):
    for j in range(i, len(final_samples)):
        group_j = final_samples[j]
        members_i = group_map[group_i]
        members_j = group_map[group_j]
        
        # Compute all pairwise similarities
        sims = []
        for a in members_i:
            for b in members_j:
                if a != b:
                    key = frozenset([a, b])
                    if key in pair_sim:
                        sims.append(pair_sim[key])
        # Self-similarity
        sim_val = 1.0 if group_i == group_j else np.mean(sims)
        records.append((group_i, group_j, sim_val))
        if group_i != group_j:
            records.append((group_j, group_i, sim_val))

# Step 6: Build final tidy and square matrix
new_tidy = pd.DataFrame(records, columns=['Sample_i', 'Sample_j', 'Similarity'])
new_matrix = new_tidy.pivot(index='Sample_i', columns='Sample_j', values='Similarity')
new_matrix = new_matrix.reindex(index=final_samples, columns=final_samples, fill_value=1.0)

# Output
print("\nTidy format after merge and deletion:")
print(new_tidy.sort_values(by=['Sample_i', 'Sample_j']).reset_index(drop=True))

print("\nNew similarity matrix:")
print(np.round(new_matrix, 3))

Tidy format after merge and deletion:
  Sample_i Sample_j  Similarity
0       S0       S0       1.000
1       S0    S1_S2       0.775
2       S0       S4       0.600
3    S1_S2       S0       0.775
4    S1_S2    S1_S2       1.000
5    S1_S2       S4       0.675
6       S4       S0       0.600
7       S4    S1_S2       0.675
8       S4       S4       1.000

New similarity matrix:
Sample_j  S1_S2     S0     S4
Sample_i
S1_S2     1.000  0.775  0.675
S0        0.775  1.000  0.600
S4        0.675  0.600  1.000

In [ ]:
sim_matrix = np.array([
    [1.0, 0.8, 0.75, 0.3, 0.6],
    [0.8, 1.0, 0.9, 0.4, 0.7],
    [0.75, 0.9, 1.0, 0.5, 0.65],
    [0.3, 0.4, 0.5, 1.0, 0.2],
    [0.6, 0.7, 0.65, 0.2, 1.0]
])

# start from here if you need new Diffusion Kernels

In [4]:
import networkx as nx
import numpy as np
from scipy.linalg import expm
import pickle
import os
import mygene
import pandas as pd
import mygene

In [12]:
def get_map_df(ensembl_ids,input_type):
    mg = mygene.MyGeneInfo()
    # Query mygene for UniProt and Entrez gene ID mappings
    results = mg.querymany(
        ensembl_ids,
        scopes=input_type,
        fields='uniprot,entrezgene',
        species='human'
    )

    results_df = pd.DataFrame(results)
    results_df = results_df[~results_df['entrezgene'].isna()]
    results_df['uniprot_ids'] = results_df['uniprot'].apply(
        lambda x: list(x.values())[0] if isinstance(x, dict) and 'Swiss-Prot' in x else None)
    results_df = results_df[~results_df['uniprot_ids'].isna()]
    results_df[results_df['uniprot_ids'].apply(lambda x: isinstance(x, list) and len(x) > 1)]
    return results_df
file_path = '/itf-fi-ml/shared/users/ziyuzh/svm/data/ppi_full_2019.txt'

G = nx.read_edgelist(file_path, nodetype=str, create_using=nx.Graph())
ensps = list(G.nodes())
del G

ppi_ids_map = get_map_df([s.split('.')[1] for s in ensps],'ensembl.protein')
ppi_set = set()
for values in ppi_ids_map['uniprot_ids']:
    if isinstance(values, list) and len(values) > 1:
        ppi_set.update(values)  # Add all elements in the list
    else:
        ppi_set.add(values)

string_ids = []
one2more = []
more2one = []  # to collect subdfs with multiple or zero matches

for uniport_ids in list(ppi_set):
    subdf = ppi_ids_map[ppi_ids_map['uniprot_ids'].str.contains(uniport_ids, na=False)]
    
    if len(subdf) == 1:
        if isinstance(subdf['uniprot_ids'], list) and len(values) > 1:
            one2more.append(subdf)
        else:
            string_ids.append(uniport_ids)
    else:
        more2one.append(subdf)

more2one_df = pd.concat(more2one, ignore_index=True)
more2one_df['string_id'] = '9606.'+more2one_df['query']
merge_dict = more2one_df.groupby('uniprot_ids')['string_id'].apply(list).to_dict()
map_dict = dict()
merge_groups = []
for key in merge_dict:
    merge_groups.append(merge_dict[key])
    new_key = '_'.join(sorted(merge_dict[key]))
    map_dict[new_key] = key
flat_set = {item for sublist in merge_groups for item in sublist}
unique_ids = ['9606.' + ensp_id for ensp_id in ppi_ids_map[ppi_ids_map['uniprot_ids'].isin(string_ids)]['query'].tolist()]
delete_list = list(set(ensps) - flat_set - set(unique_ids))
sample_names = ensps

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
2 input query terms found dup hits:	[('ENSP00000319979', 2), ('ENSP00000473163', 3)]
1957 input query terms found no hit:	['ENSP00000415070', 'ENSP00000267197', 'ENSP00000415452', 'ENSP00000006101', 'ENSP00000262477', 'ENS

In [36]:
len(merge_groups),len(flat_set),len(unique_ids)

(72, 168, 17151)

In [19]:
len(merge_groups),len(flat_set),len(unique_ids)

(71, 166, 17137)

In [ ]:
# map_dict: dict, key is '_'.joint(merge ensp ids), value is corresponding uniport id
# flat_set: keys in map_dict
# unique_ids: unique ensps don't need convert

In [20]:
# to do: add unique id maps to map_dict
unique_df = ppi_ids_map[ppi_ids_map['uniprot_ids'].isin(string_ids)][['query','uniprot_ids']]
unique_df['string_ids'] = '9606.' + unique_df['query']
unique_mapping_dict = unique_df.set_index('string_ids')['uniprot_ids'].to_dict()
map_dict.update(unique_mapping_dict)
len(map_dict)

17208

In [7]:
# to do: add unique id maps to map_dict
unique_df = ppi_ids_map[ppi_ids_map['uniprot_ids'].isin(string_ids)][['query','uniprot_ids']]
unique_df['string_ids'] = '9606.' + unique_df['query']
unique_mapping_dict = unique_df.set_index('string_ids')['uniprot_ids'].to_dict()
map_dict.update(unique_mapping_dict)
len(map_dict)

17208

In [43]:
diffusion_uniports = [value for key, value in map_dict.items()]
len(diffusion_uniports)

17223

In [21]:
diffusion_uniports = [value for key, value in map_dict.items()]
len(diffusion_uniports)

17208

In [9]:
from features_reindex import get_feature
from sklearn.preprocessing import MinMaxScaler
merged_df = None

root = '/itf-fi-ml/shared/users/ziyuzh/svm'
# time_feature_list = ['uniport_ppi_2019','ppi_2019_dw_40','uniport_bio','uniport_seq','uniport_esm']
time_feature_list = ['uniport_ppi_2019','ppi_2019_dw_40','text','uniport_bio','uniport_seq','uniport_esm']

feature_list = time_feature_list
for feature in time_feature_list:
    feature_df = get_feature(root, feature)

    feature_cols = [col for col in feature_df.columns if col.startswith('feature')]
    if feature_cols:
        scaler = MinMaxScaler()
        feature_df[feature_cols] = scaler.fit_transform(feature_df[feature_cols])

    # Rename columns starting with 'feature'
    feature_df.rename(columns={
        col: f"{feature}_{col}" if col.startswith('feature') else col
        for col in feature_df.columns
    }, inplace=True)

    # Merge iteratively to avoid keeping all DataFrames
    if merged_df is None:
        merged_df = feature_df
    else:
        merged_df = pd.merge(merged_df, feature_df, on='string_id', how='inner')
    del feature_df  # Free memory
name_list = feature_list + ['string_id']

merged_df = merged_df[[col for col in merged_df.columns if any(item in col for item in name_list)]]

In [28]:
len(merged_df)

15686

In [10]:
len(merged_df)

12684

In [47]:
len(set(diffusion_uniports)-set(merged_df['string_id'].tolist())), len(set(merged_df['string_id'].tolist())-set(diffusion_uniports))

(1537, 0)

In [22]:
len(set(diffusion_uniports)-set(merged_df['string_id'].tolist())), len(set(merged_df['string_id'].tolist())-set(diffusion_uniports))

(4534, 10)

In [23]:
delete_uniports = set(diffusion_uniports)-set(merged_df['string_id'].tolist())

In [24]:
map_dict_aligned = dict()
mapped_ensp = []
for key, value in map_dict.items():
    if value in delete_uniports:
        pass
    else:
        map_dict_aligned[key] = value
        mapped_ensp.extend(key.split('_'))

In [55]:
len(map_dict_aligned),len(mapped_ensp)

(15686, 15770)

In [25]:
len(map_dict_aligned),len(mapped_ensp)

(12674, 12716)

In [26]:
delete_ensp = list(set(ensps) - set(mapped_ensp))

In [58]:
len(delete_ensp),len(map_dict_aligned)

(3806, 15686)

In [27]:
len(delete_ensp),len(map_dict_aligned)

(6860, 12674)

In [28]:
recalculate = []
for key, value in map_dict_aligned.items():
    if '_' in key:
        recalculate.append(key.split('_'))

In [67]:
len(recalculate)

65

In [29]:
len(recalculate)

33

In [30]:
recalculate[0]

['9606.ENSP00000298815', '9606.ENSP00000303999']

In [76]:
with open('/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019_map.pkl', 'wb') as f:
    pickle.dump([recalculate,delete_ensp,map_dict_aligned], f)

In [31]:
folder_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/df_align_text'
os.makedirs(folder_path, exist_ok=True)

with open(os.path.join(folder_path,'2019_map.pkl'), 'wb') as f:
    pickle.dump([recalculate,delete_ensp,map_dict_aligned], f)

# after get diffusion kernels, merge information into the kernel_dict and create a feature df for diffusion kernel, in this case, only use the ids and its position into merged_df

In [1]:
import pickle
import os

In [2]:

# Set the directory where your files are located
directory = "/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019"

# Loop through all files in the directory
for filename in os.listdir(directory):
    if "difussion" in filename:
        new_filename = filename.replace("difussion", "diffusion")
        old_path = os.path.join(directory, filename)
        new_path = os.path.join(directory, new_filename)
        os.rename(old_path, new_path)
        print(f"Renamed: {filename} -> {new_filename}")

Renamed: difussion_logK_0.5.pkl -> diffusion_logK_0.5.pkl
Renamed: uniport_ids_difussion_K_0.1.pkl -> uniport_ids_diffusion_K_0.1.pkl
Renamed: uniport_difussion_logK_2.pkl -> uniport_diffusion_logK_2.pkl
Renamed: difussion_logK_0.8.pkl -> diffusion_logK_0.8.pkl
Renamed: difussion_K_2.pkl -> diffusion_K_2.pkl
Renamed: difussion_K_0.5.pkl -> diffusion_K_0.5.pkl
Renamed: uniport_difussion_logK_1.pkl -> uniport_diffusion_logK_1.pkl
Renamed: difussion_logK_2.pkl -> diffusion_logK_2.pkl
Renamed: uniport_difussion_logK_0.5.pkl -> uniport_diffusion_logK_0.5.pkl
Renamed: difussion_K_0.2.pkl -> diffusion_K_0.2.pkl
Renamed: uniport_ids_difussion_K_2.pkl -> uniport_ids_diffusion_K_2.pkl
Renamed: uniport_ids_difussion_K_0.8.pkl -> uniport_ids_diffusion_K_0.8.pkl
Renamed: uniport_ids_difussion_K_0.5.pkl -> uniport_ids_diffusion_K_0.5.pkl
Renamed: difussion_K_0.1.pkl -> diffusion_K_0.1.pkl
Renamed: uniport_difussion_K_0.1.pkl -> uniport_diffusion_K_0.1.pkl
Renamed: uniport_difussion_logK_0.8.pkl -> uniport_diffusion_logK_0.8.pkl
Renamed: uniport_difussion_K_1.pkl -> uniport_diffusion_K_1.pkl
Renamed: difussion_logK_1.pkl -> diffusion_logK_1.pkl
Renamed: uniport_difussion_K_0.5.pkl -> uniport_diffusion_K_0.5.pkl
Renamed: uniport_ids_difussion_K_0.2.pkl -> uniport_ids_diffusion_K_0.2.pkl
Renamed: uniport_difussion_logK_0.1.pkl -> uniport_diffusion_logK_0.1.pkl
Renamed: difussion_K_0.8.pkl -> diffusion_K_0.8.pkl
Renamed: difussion_K_1.pkl -> diffusion_K_1.pkl
Renamed: uniport_difussion_K_0.2.pkl -> uniport_diffusion_K_0.2.pkl
Renamed: uniport_difussion_K_0.8.pkl -> uniport_diffusion_K_0.8.pkl
Renamed: uniport_difussion_logK_0.2.pkl -> uniport_diffusion_logK_0.2.pkl
Renamed: uniport_ids_difussion_K_1.pkl -> uniport_ids_diffusion_K_1.pkl
Renamed: difussion_logK_0.2.pkl -> diffusion_logK_0.2.pkl
Renamed: uniport_difussion_K_2.pkl -> uniport_diffusion_K_2.pkl
Renamed: difussion_logK_0.1.pkl -> diffusion_logK_0.1.pkl

In [5]:
kernel_dict_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/path_save.pkl'
with open(kernel_dict_path, 'rb') as f:
    kernels_all_dict = pickle.load(f)

In [6]:
kernels_all_dict.keys()

dict_keys(['ppi_2019_dw_40', 'uniport_seq', 'uniport_esm', 'uniport_bio', 'uniport_ppi_2019'])

In [7]:
df_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019'
df_dict = dict()
for file in os.listdir(df_path):
    if 'uniport_diffusion_K' in file:
        temp_list = []
        key = file.split('_')[-1][:-4]
        temp_list.append(os.path.join(df_path,file))
        temp_list.append(os.path.join(df_path,'uniport_diffusion_logK_'+file.split('_')[-1]))
        df_dict[key] = temp_list

In [8]:
df_dict

{'0.2': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.2.pkl',
  '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.2.pkl'],
 '1': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_1.pkl',
  '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_1.pkl'],
 '0.5': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.5.pkl',
  '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.5.pkl'],
 '2': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_2.pkl',
  '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_2.pkl'],
 '0.1': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.1.pkl',
  '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.1.pkl'],
 '0.8': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.8.pkl',
  '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.8.pkl']}

In [10]:
path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.1.pkl'
# path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_difussion_logK_0.1.pkl'

with open(path, 'rb') as f:
    test_k = pickle.load(f)

In [19]:
# # Rename key 'difussion_model' to 'diffusion_model'
# if "diffusion_kernel" in kernels_all_dict:
#     kernels_all_dict["diffusion_2019"] = kernels_all_dict.pop("diffusion_kernel")

# print(kernels_all_dict)

In [ ]:
kernels_all_dict['diffusion_2019'] = df_dict

In [12]:
kernels_all_dict

{'ppi_2019_dw_40': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_2_0.48138034733416246.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_2_0.48138034733416246.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_4_0.24069017366708123.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_4_0.24069017366708123.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_K_8_0.12034508683354062.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/ppi_2019_dw_40_logK_8_0.12034508683354062.pkl']},
 'uniport_seq': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_2_0.22444018226022353.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_2_0.22444018226022353.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_4_0.11222009113011176.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_4_0.11222009113011176.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_K_8_0.05611004556505588.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_seq_logK_8_0.05611004556505588.pkl']},
 'uniport_esm': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_2_0.11355235622105712.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_2_0.11355235622105712.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_4_0.05677617811052856.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_4_0.05677617811052856.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_K_8_0.02838808905526428.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_esm_logK_8_0.02838808905526428.pkl']},
 'uniport_bio': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_2_0.5427586367192363.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_2_0.5427586367192363.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_4_0.27137931835961815.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_4_0.27137931835961815.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_K_8_0.13568965917980907.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_bio_logK_8_0.13568965917980907.pkl']},
 'uniport_ppi_2019': {2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_2_0.5052695526173884.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_2_0.5052695526173884.pkl'],
  4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_4_0.2526347763086942.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_4_0.2526347763086942.pkl'],
  8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_K_8_0.1263173881543471.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/uniport_ppi_2019_logK_8_0.1263173881543471.pkl']},
 'diffusion_kernel': {'0.2': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.2.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.2.pkl'],
  '1': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_1.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_1.pkl'],
  '0.5': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.5.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.5.pkl'],
  '2': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_2.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_2.pkl'],
  '0.1': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.1.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.1.pkl'],
  '0.8': ['/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_0.8.pkl',
   '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_logK_0.8.pkl']}}

In [13]:
with open(kernel_dict_path, 'wb') as f:
    pickle.dump(kernels_all_dict, f)

In [23]:
'/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm/2019/path_save.pkl'
kernel_dir_path = os.path.join('/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm',str(2019))

os.makedirs(kernel_dir_path, exist_ok=True)
kernel_pkl_path = os.path.join(kernel_dir_path,'path_save.pkl')

if os.path.isfile(kernel_pkl_path):
    print('kernels existing')
    with open(kernel_pkl_path, 'rb') as f:
        kernels_all_dict = pickle.load(f)
else:
    kernels_all_dict = dict()
feature_list = ['diffusion_2019']
add_feature_list = set(feature_list) - set(kernels_all_dict.keys())

kernels existing

In [14]:
id_lists = []
for file in os.listdir(df_path):
    if 'uniport_ids' in file:
        id_path = os.path.join(df_path,file)
        with open(id_path, 'rb') as f:
            id_list = pickle.load(f)
        id_lists.append(id_list)

In [15]:
if id_lists[0] == id_lists[1]:
    print(1)

1

In [16]:
# check if the ids are same (including order), if they are same:
# Convert to DataFrame
import pandas as pd
df = pd.DataFrame({
    'string_id': id_lists[0],
    'feature_0': range(len(id_lists[0]))
})
df.to_csv('/itf-fi-ml/shared/users/ziyuzh/svm/data/diffusion_2019.csv',index=False)

In [3]:
import pandas as pd
import pickle
import numpy as np

In [4]:
df_kernel_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_diffusion_K_2.pkl'
with open(df_kernel_path, 'rb') as f:
    df_kernel = pickle.load(f)

In [6]:
df_kernel_ids_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/df/2019/uniport_ids_diffusion_K_2.pkl'
with open(df_kernel_ids_path, 'rb') as f:
    df_kernel_ids = pickle.load(f)

In [7]:
df_kernel.shape,df_kernel_ids[0]

((15686, 15686), 'A6NI28')

In [13]:
df = pd.DataFrame(
    df_kernel,
    index=df_kernel_ids,
    columns=[f"feature_{i}" for i in range(df_kernel.shape[1])]
)

# Name the index
df.index.name = "string_id"

In [14]:
df.head(3)

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_15676,feature_15677,feature_15678,feature_15679,feature_15680,feature_15681,feature_15682,feature_15683,feature_15684,feature_15685
string_id,,,,,,,,,,,,,,,,,,,,,
A6NI28,1.000001,0.000004,0.000003,0.000003,0.000009,0.000008,7.203622e-07,0.000002,0.000002,0.000010,...,0.000004,0.000014,0.000007,0.000014,0.000001,0.000021,0.000011,0.000008,0.000001,0.000010
O00233,0.000004,1.000001,0.000010,0.000013,0.000015,0.000016,2.783302e-06,0.000011,0.000017,0.000019,...,0.000046,0.000022,0.000194,0.000021,0.000002,0.000023,0.000054,0.000312,0.000004,0.000053
O14598,0.000003,0.000010,1.000001,0.001184,0.000020,0.000137,2.427001e-06,0.000004,0.000020,0.000006,...,0.000019,0.000013,0.000016,0.000014,0.000001,0.000008,0.000024,0.000016,0.000004,0.000020

In [12]:
# Select only numeric columns
numeric_df = df.select_dtypes(include="number")

min_val = numeric_df.min().min()
max_val = numeric_df.max().max()
mean_val = numeric_df.values.mean()

print("Min:", min_val)
print("Max:", max_val)
print("Mean:", mean_val)

Min: 3.323771361560415e-09
Max: 1.000001
Mean: 0.0001009450361191195

In [15]:
df = df.reset_index()
df.to_csv('/itf-fi-ml/shared/users/ziyuzh/svm/data/diffusion_2019_2.csv',index=False)

# check kernel sym

In [10]:
X_k_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_bio_K_2_0.05853505840227169.pkl'
X_logk_path = '/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc/2019/uniport_bio_logK_2_0.05853505840227169.pkl'

In [ ]:
with open(X_k_path, 'rb') as f:
    X_k = pickle.load(f)
with open(X_logk_path, 'rb') as f:
    X_logk = pickle.load(f)

ks = [X_k]
logks = [X_logk]

def normalize_kernel(K):
    diag = np.sqrt(np.diag(K))
    diag[diag == 0] = 1e-8  # Avoid division by zero
    return K / (diag[:, None] * diag[None, :])

In [13]:
K_linear_fused = np.mean(ks, axis=0)

np.array_equal(K_linear_fused, X_k)

True

In [16]:
K_linear_fused = 0.5 * (K_linear_fused + K_linear_fused.T)
np.array_equal(K_linear_fused, X_k), np.allclose(K_linear_fused, X_k)

(False, True)

In [17]:
K_linear_fused = normalize_kernel(K_linear_fused)
np.array_equal(K_linear_fused, X_k), np.allclose(K_linear_fused, X_k)

(False, True)

In [ ]:
logk_avg = np.mean(logks, axis=0)
eigenvalues, eigenvectors = np.linalg.eigh(logk_avg)
eigenvalues = np.clip(eigenvalues, -50, 50)  # Prevent overflow
K_geo_mean = eigenvectors @ np.diag(np.exp(eigenvalues)) @ eigenvectors.T
np.array_equal(K_geo_mean, X_k), np.allclose(K_geo_mean, X_k)

(False, True)

In [20]:
X_k_sym = 0.5 * (X_k + X_k.T)
K_linear_fused = np.mean([X_k_sym], axis=0)
K_linear_fused = 0.5 * (K_linear_fused + K_linear_fused.T)
K_linear_fused = normalize_kernel(K_linear_fused)
np.array_equal(K_linear_fused, X_k_sym), np.allclose(K_linear_fused, X_k_sym)

(True, True)

In [ ]:
def process_kernel(args):
    K= args

    eigenvalues, eigenvectors = np.linalg.eigh(K)
    eigenvalues = np.clip(eigenvalues, 1e-12, None)  # Avoid log(0)
    K_log = eigenvectors @ np.diag(np.log(eigenvalues)) @ eigenvectors.T
    K_log = 0.5 * (K_log + K_log.T)

    return K_log

logm_k_sym = process_kernel(X_k_sym)

logk_avg = np.mean([logm_k_sym], axis=0)
eigenvalues, eigenvectors = np.linalg.eigh(logk_avg)
eigenvalues = np.clip(eigenvalues, -50, 50)  # Prevent overflow
K_geo_mean = eigenvectors @ np.diag(np.exp(eigenvalues)) @ eigenvectors.T
np.array_equal(K_geo_mean, X_k_sym), np.allclose(K_geo_mean, X_k_sym)

(False, True)

In [24]:
# Load the same kernel used in select_gamma_ratio
with open('/itf-fi-ml/shared/users/ziyuzh/svm/results/dw_auc_norm_test/2019/uniport_bio_K_2_0.5427586367192363.pkl', 'rb') as f:
    X_k = pickle.load(f)

K_linear_fused = np.mean([X_k], axis=0)
K_linear_fused = 0.5 * (K_linear_fused + K_linear_fused.T)
K_linear_fused = normalize_kernel(K_linear_fused)

# Compare to your fused version
np.allclose(X_k, K_linear_fused) , np.allclose(normalize_kernel(X_k), K_linear_fused)  # Might be closer to True

(True, True)

In [27]:
import pandas as pd
import numpy as np

# Create a DataFrame with 4 columns and 100 rows of random values between 0 and 1
df = pd.DataFrame(np.random.rand(100, 4), columns=['A', 'B', 'C', 'D'])

In [28]:
df.sample(n=10, replace=True, random_state=42)

           A         B         C         D
51  0.462025  0.275829  0.112412  0.238344
92  0.745503  0.293508  0.102453  0.494458
14  0.983508  0.363192  0.966372  0.799653
71  0.095200  0.610888  0.283372  0.885774
60  0.676524  0.186099  0.905720  0.158129
20  0.473807  0.596660  0.633599  0.276020
82  0.258661  0.125689  0.488922  0.896569
86  0.113321  0.263151  0.922083  0.336097
74  0.215723  0.524986  0.683844  0.462290
74  0.215723  0.524986  0.683844  0.462290

In [29]:
df.sample(n=10, replace=True, random_state=42)

           A         B         C         D
51  0.462025  0.275829  0.112412  0.238344
92  0.745503  0.293508  0.102453  0.494458
14  0.983508  0.363192  0.966372  0.799653
71  0.095200  0.610888  0.283372  0.885774
60  0.676524  0.186099  0.905720  0.158129
20  0.473807  0.596660  0.633599  0.276020
82  0.258661  0.125689  0.488922  0.896569
86  0.113321  0.263151  0.922083  0.336097
74  0.215723  0.524986  0.683844  0.462290
74  0.215723  0.524986  0.683844  0.462290